name: Xm assessment API linter
on:
  push:
    branches: [ master ]
  pull_request:
permissions:
  contents: read
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
