name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x]

    name: Unit tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run the tests
        run: go test -short -count=1 ./...
